[package]
name = "mm2_eth"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
ethabi = { git = "https://github.com/artemii235/ethabi" }
ethkey = { git = "https://github.com/artemii235/parity-ethereum.git" }
ethereum-types = { version = "0.4", default-features = false, features = ["std", "serialize"] }
hex.workspace = true
indexmap = { version = "1.7", features = ["serde-1"] }
mm2_err_handle.workspace = true
secp256k1 = { version = "0.20", features = ["recovery"] }
serde.workspace = true
serde_json.workspace = true
tiny-keccak = { version = "2.0", features = ["keccak"] }
web3 = { git = "https://github.com/artemii235/rust-web3", default-features = false }
