[package]
name = "proxy_signature"
version = "0.1.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
chrono.workspace = true
http.workspace = true
serde.workspace = true
serde_json.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
libp2p = { git = "https://github.com/libp2p/rust-libp2p.git", default-features = false, features = ["secp256k1", "tcp-tokio"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
libp2p = { git = "https://github.com/libp2p/rust-libp2p.git", default-features = false, features = ["secp256k1", "wasm-ext"] }

[dev-dependencies]
rand = { version = "0.7", features = ["std", "small_rng"] }
