[package]
edition = "2021"
name = "chain"
version = "0.1.0"
authors = ["debris <marek.kotewicz@gmail.com>"]

[dependencies]
rustc-hex = "2"
bitcoin = "0.27.1"
kdf_crypto = { path = "../../kdf_crypto" }
primitives = { package = "kdf_primitives", path = "../../kdf_primitives" }
serialization = { package = "kdf_codec", path = "../../kdf_codec" }
serialization_derive = { package = "kdf_codec_derive", path = "../../kdf_codec_derive" }
